version: "3.9"
services:
  worker:
    build: .
    environment:
      WEBHOOK: $WEBHOOK
      TG_BOT_TOKEN: $TG_BOT_TOKEN
      UPDATE_CHANNEL: $UPDATE_CHANNEL
      APP_ID: $APP_ID
      API_HASH: $API_HASH
      BANNED_USERS: $BANNED_USERS
      CHUNK_SIZE: $CHUNK_SIZE
